package eu.uqasar.adapter.model;


public enum uQasarMetric {
    PROJECTS_PER_SYSTEM_INSTANCE ,
    ISSUES_PER_PROJECTS_PER_SYSTEM_INSTANCE,
    FIXED_ISSUES_PER_PROJECT,
    UNRESOLVED_ISSUES_PER_PROJECT,
    UNRESOLVED_BUG_ISSUES_PER_PROJECT,
    UNRESOLVED_TASK_ISSUES_PER_PROJECT


}
